### ISSUE TITLE
Delete pycache folder

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/volpiano-display-utilities#15]
The pycache folder isn’t supposed to be committed to source control as it’s the compiled machine code, and Python autogenerates this on demand.

**Comment by ahankinson** [comment]
You also shouldn't include the whl and tar.gz files in the repo. If you want to distrubute them, create them locally and upload them as attachments to the release.

**Comment by dchiller** [comment]
Thanks @ahankinson for catching this! Resolved now.
