### ISSUE TITLE
align_text_and_volpiano errors when Volpiano is just a clef

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/volpiano-display-utilities#44]
working on something in my local CantusDB setup, I made a chant with volpiano of only `1`. Upon saving the chant, I got this traceback upon landing on the chant detail page.

![Screenshot 2024-03-08 at 3 40 29 PM](https://github.com/DDMAL/volpiano-display-utilities/assets/58090591/8b354f45-9993-4035-b121-b082e4f1fe82)

Very much an edge case. Not sure what the behavior should be for this situation, but it probably shouldn't be an unhandled exception.

**Comment by dchiller** [comment]
Good catch!

**Comment by jacobdgm** [comment]
(I think we're already in agreement that this needs to be fixed. I don't see any high-medium-low–priority tags on this repo, but this should be marked as medium-high, I think. If a user makes a mistake and enters a 1-character string in the volpiano field, they lose access to the Chant Edit page, i.e., there's no way to correct the chant without going into the Admin area)

**Comment by dchiller** [comment]
I will make those tags right now and add them here. I think medium-high is correct.
