### ISSUE TITLE
Syllabification improperly handles "suavissimum"

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/volpiano-display-utilities#45]
In an email from Debra:

> "Suavissimum" is being split into too many syllables here. "sua" should be just one in this case. But in the case of the single word "sua" it would be two syllables.
> 
> https://cantusdatabase.org/chant/588598
> 
> Is our system able to handle this?

**Comment by dchiller** [comment]
Catching up on this now....

From @annamorphism's email, it looks like there are differences in the syllabification of this word (and of `suav` constructions generally) that we want to maintain, and that this will be a place where manual editing in one case or another will be necessary.

Is that a correct reading of the discussion?

@annamorphism, can you confirm that "su-a" is what we want as default and "sua" is an 'exception' that we will make manually? I think that's what your email says, but before I close this issue I want to make sure.

**Comment by annamorphism** [comment]
Correct: as far as I can tell, su-a is applicable in more cases than "sua" (both in more words and in more examples of each of those words), so it should remain the default. (It would be interesting to have some sort of way of flagging the exceptions: "an extra syllable was found in the following chants" or maybe even "the following chants have unmatched Volpiano on the word 'suavissimum'." But that's a problem for another time!)

**Comment by dchiller** [comment]
I think this type of message is captured under #5 (so a very useful enhancement, but definitely an enhancement).

Thanks for confirming...closing this since we've determined we want to keep current behaviour with this construction.
