### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/volpiano-display-utilities#53]
Linking https://github.com/DDMAL/CantusDB/issues/1485 here because it seems like this is more of an issue with the volpiano display utilities

**Comment by dchiller** [comment]
This was actually solved with #51, but a new release had not yet been created and used in CantusDB. This new release is now created https://github.com/DDMAL/volpiano-display-utilities/releases/tag/v1.1.3
